import type { ComponentType } from 'react';
import {
  SiPython,
  SiNodedotjs,
  SiReact,
  SiTypescript,
  SiNextdotjs,
  SiFigma,
  SiPostgresql,
  SiDocker,
  SiKubernetes,
  SiMongodb,
  SiRedis,
  SiGooglecloud,
  SiJavascript,
  SiTailwindcss,
  SiGraphql,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiVuedotjs,
  SiAngular,
  SiGo,
  SiRust,
  SiCplusplus,
  SiPhp,
  SiLaravel,
  SiDjango,
  SiFastapi,
  SiSupabase,
  SiFirebase,
  SiMysql,
  SiPrisma,
  SiTerraform,
  SiGithubactions,
  SiLinux,
  SiNginx,
  SiApachekafka,
  SiElasticsearch,
  SiAndroid,
  SiApple,
  SiGit,
  SiHtml5,
  SiVite,
  SiPostman,
  SiDotnet
} from 'react-icons/si';
import { FaAws, FaJava, FaCss3Alt } from 'react-icons/fa6';
import { TbBrandOpenai, TbBrandCSharp } from 'react-icons/tb';

export interface TechItem {
  name: string;
  icon: ComponentType<{ size?: number; className?: string; style?: React.CSSProperties }>;
  color: string;
}

export const TECH_STACK: TechItem[] = [
  { name: 'Python', icon: SiPython, color: '#3776AB' },
  { name: 'AWS', icon: FaAws, color: '#FF9900' },
  { name: 'Node.js', icon: SiNodedotjs, color: '#5FA04E' },
  { name: 'React', icon: SiReact, color: '#61DAFB' },
  { name: 'TypeScript', icon: SiTypescript, color: '#3178C6' },
  { name: 'Next.js', icon: SiNextdotjs, color: '#FFFFFF' },
  { name: 'Figma', icon: SiFigma, color: '#F24E1E' },
  { name: 'PostgreSQL', icon: SiPostgresql, color: '#4169E1' },
  { name: 'Docker', icon: SiDocker, color: '#2496ED' },
  { name: 'Kubernetes', icon: SiKubernetes, color: '#326CE5' },
  { name: 'MongoDB', icon: SiMongodb, color: '#47A248' },
  { name: 'Redis', icon: SiRedis, color: '#DC382D' },
  { name: 'Google Cloud', icon: SiGooglecloud, color: '#4285F4' },
  { name: 'JavaScript', icon: SiJavascript, color: '#F7DF1E' },
  { name: 'Java', icon: FaJava, color: '#ED8B00' },
  { name: 'Tailwind CSS', icon: SiTailwindcss, color: '#06B6D4' },
  { name: 'GraphQL', icon: SiGraphql, color: '#E10098' },
  { name: 'Flutter', icon: SiFlutter, color: '#02569B' },
  { name: 'Swift', icon: SiSwift, color: '#F05138' },
  { name: 'Kotlin', icon: SiKotlin, color: '#7F52FF' },
  { name: 'Vue.js', icon: SiVuedotjs, color: '#4FC08D' },
  { name: 'Angular', icon: SiAngular, color: '#DD0031' },
  { name: 'Go', icon: SiGo, color: '#00ADD8' },
  { name: 'Rust', icon: SiRust, color: '#DEA584' },
  { name: 'C++', icon: SiCplusplus, color: '#00599C' },
  { name: 'C#', icon: TbBrandCSharp, color: '#239120' },
  { name: '.NET', icon: SiDotnet, color: '#512BD4' },
  { name: 'OpenAI', icon: TbBrandOpenai, color: '#10A37F' },
  { name: 'PHP', icon: SiPhp, color: '#777BB4' },
  { name: 'Laravel', icon: SiLaravel, color: '#FF2D20' },
  { name: 'Django', icon: SiDjango, color: '#44B78B' },
  { name: 'FastAPI', icon: SiFastapi, color: '#009688' },
  { name: 'Supabase', icon: SiSupabase, color: '#3ECF8E' },
  { name: 'Firebase', icon: SiFirebase, color: '#FFCA28' },
  { name: 'MySQL', icon: SiMysql, color: '#4479A1' },
  { name: 'Prisma', icon: SiPrisma, color: '#2D3748' },
  { name: 'Terraform', icon: SiTerraform, color: '#844FBA' },
  { name: 'GitHub Actions', icon: SiGithubactions, color: '#2088FF' },
  { name: 'Linux', icon: SiLinux, color: '#FCC624' },
  { name: 'Nginx', icon: SiNginx, color: '#009639' },
  { name: 'Apache Kafka', icon: SiApachekafka, color: '#FFFFFF' },
  { name: 'Elasticsearch', icon: SiElasticsearch, color: '#005571' },
  { name: 'Android', icon: SiAndroid, color: '#3DDC84' },
  { name: 'Apple / iOS', icon: SiApple, color: '#A2AAAD' },
  { name: 'Git', icon: SiGit, color: '#F05032' },
  { name: 'HTML5', icon: SiHtml5, color: '#E34F26' },
  { name: 'CSS3', icon: FaCss3Alt, color: '#1572B6' },
  { name: 'Vite', icon: SiVite, color: '#646CFF' },
  { name: 'Postman', icon: SiPostman, color: '#FF6C37' }
];
